name: scPerturb dataset info
datasets:
  dataset_info:
    path: "scperturb_dataset_info_test.csv"
default-view: dataset_info
views:
  dataset_info:
    dataset: dataset_info
    desc: |
      ### scPerturb
      This table contains info about single-cell perturbation datasets included in [scPerturb](http://projects.sanderlab.org/scperturb/).
      You can use the blue download buttons on the left to download a dataset of interest. You can also download this table as an excel sheet with the second button on the top right of this page.
      For more info see [Github](https://github.com/sanderlab/scPerturb) or our [paper](https://doi.org/10.1101/2022.08.20.504663).
    page-size: 25
    render-table:
      columns:
        Download Link:
          link-to-url: "https://zenodo.org/record/{Zenodo ID}/files/{Full index}.{File Extension}"
        Full index:
          display-mode: hidden
        Zenodo ID:
          display-mode: hidden
        File Extension:
          display-mode: hidden
        Title:
          link-to-url: "{doi_url}"
        Disease:
          display-mode: detail
        Cell Type:
          display-mode: detail
        Tissues:
          display-mode: detail
        Tissue Type:
          display-mode: detail
        Organisms:
          display-mode: detail
        doi_url:
          display-mode: hidden
        multiple_time_points:
          display-mode: hidden
        multiple_concentrations:
          display-mode: hidden
        combined_perturbations:
          display-mode: hidden
        Date_of_Submission :
          display-mode: hidden
        Modality:
          plot:
            heatmap:
              scale: ordinal
              domain:
                - "RNA"
                - "RNA + protein (RNA)"
                - "ATAC"
                - "ATAC + protein"
                - "RNA + protein (protein)"
              range:
                - "#1f77b4"
                - "#1f77b4"
                - "#ff7f0e"
                - "#bcbd22"
                - "#d62728"
        Cancer:
          plot:
            heatmap:
              scale: ordinal
              domain:
                - y
                - n
              range:
                - "#2CA02C"
                - "#D62728"
        Number Of Perturbations:
          ellipsis: 5
        Year:
          plot:
            ticks:
              scale: linear
              domain:
                - 2016
                - 2023
